package app.plugin.collection;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/** Owns the project-local H2 database and its versioned schema. */
public final class CollectionDatabase implements AutoCloseable {
    public static final int SCHEMA_VERSION = 2;
    private static final DateTimeFormatter BACKUP_TIME = DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss");

    private final Path root;
    private final String jdbcUrl;
    private Connection connection;
    private boolean closed;

    public CollectionDatabase(Path projectDirectory) throws IOException, SQLException {
        this(projectDirectory.resolve("private_collection"), null);
    }

    CollectionDatabase(Path root, String overrideUrl) throws IOException, SQLException {
        this.root = root.toAbsolutePath().normalize();
        Files.createDirectories(this.root);
        Files.createDirectories(photosDirectory());
        Files.createDirectories(labelsDirectory());
        Files.createDirectories(exportsDirectory());
        Files.createDirectories(backupsDirectory());
        Path base = this.root.resolve("collection");
        this.jdbcUrl = overrideUrl != null ? overrideUrl
                : "jdbc:h2:file:" + base.toString().replace('\\', '/') + ";AUTO_SERVER=FALSE";
        open();
        migrate();
    }

    static CollectionDatabase inMemory(String name, Path workRoot) throws IOException, SQLException {
        return new CollectionDatabase(workRoot, "jdbc:h2:mem:" + name + ";DB_CLOSE_DELAY=-1");
    }

    public Path root() { return root; }
    public Path photosDirectory() { return root.resolve("photos"); }
    public Path labelsDirectory() { return root.resolve("labels"); }
    public Path exportsDirectory() { return root.resolve("exports"); }
    public Path backupsDirectory() { return root.resolve("backups"); }

    synchronized Connection connection() throws SQLException {
        if (closed) throw new SQLException("Collection database is closed");
        if (connection == null || connection.isClosed()) open();
        return connection;
    }

    private void open() throws SQLException {
        if (closed) throw new SQLException("Collection database is closed");
        connection = DriverManager.getConnection(jdbcUrl, "sa", "");
    }

    private void migrate() throws SQLException, IOException {
        int current = readVersion();
        if (current > SCHEMA_VERSION) {
            throw new SQLException("Collection database schema " + current
                    + " is newer than this MiniMap version (" + SCHEMA_VERSION + ")");
        }
        if (current > 0 && current < SCHEMA_VERSION && jdbcUrl.startsWith("jdbc:h2:file:")) {
            closeConnection();
            Path source = root.resolve("collection.mv.db");
            if (Files.isRegularFile(source)) {
                Files.copy(source, backupsDirectory().resolve("collection-before-v" + SCHEMA_VERSION + "-"
                                + BACKUP_TIME.format(LocalDateTime.now()) + ".mv.db"),
                        StandardCopyOption.COPY_ATTRIBUTES);
            }
            open();
        }

        Connection c = connection();
        boolean oldAutoCommit = c.getAutoCommit();
        c.setAutoCommit(false);
        try {
            // Separate ifs, not else-if: a fresh database runs every step in turn and readVersion takes MAX(version).
            if (current == 0) createVersionOne(c);
            if (current < 2) createVersionTwo(c);
            c.commit();
        } catch (Exception e) {
            c.rollback();
            if (e instanceof SQLException sql) throw sql;
            throw new SQLException("Could not migrate collection database", e);
        } finally {
            c.setAutoCommit(oldAutoCommit);
        }
    }

    private int readVersion() throws SQLException {
        try (ResultSet rs = connection().getMetaData().getTables(null, null, "SCHEMA_VERSION", null)) {
            if (!rs.next()) return 0;
        }
        try (Statement s = connection().createStatement();
             ResultSet rs = s.executeQuery("SELECT MAX(version) FROM schema_version")) {
            return rs.next() ? rs.getInt(1) : 0;
        }
    }

    private static void createVersionOne(Connection c) throws SQLException {
        String[] statements = {
                "CREATE TABLE schema_version(version INT PRIMARY KEY, installed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                "CREATE TABLE collection_setting(setting_key VARCHAR(100) PRIMARY KEY, setting_value VARCHAR(1000) NOT NULL)",
                "CREATE TABLE person(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, full_name VARCHAR(255) NOT NULL, short_name VARCHAR(100), artportalen_name VARCHAR(255), UNIQUE(full_name))",
                "CREATE TABLE locality(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL, short_name VARCHAR(100), country_code VARCHAR(2), country_name VARCHAR(100), province VARCHAR(150), district VARCHAR(150), description VARCHAR(1000), latitude DOUBLE, longitude DOUBLE, uncertainty_m INT, coordinate_source VARCHAR(30) NOT NULL DEFAULT 'TEXT_ONLY', nearest_place VARCHAR(255), nearest_distance_m INT, nearest_direction VARCHAR(8), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK ((latitude IS NULL AND longitude IS NULL) OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)))",
                "CREATE TABLE collection_event(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, locality_id BIGINT NOT NULL REFERENCES locality(id), kind VARCHAR(20) NOT NULL, field_number VARCHAR(100), start_date DATE, end_date DATE, local_time TIME, end_time TIME, timezone VARCHAR(80), utc_datetime TIMESTAMP WITH TIME ZONE, latitude DOUBLE, longitude DOUBLE, uncertainty_m INT, elevation_m DOUBLE, coordinate_source VARCHAR(30) NOT NULL DEFAULT 'LOCALITY_FALLBACK', method VARCHAR(150), trap_number VARCHAR(100), expected_count INT NOT NULL DEFAULT 0, habitat VARCHAR(1000), notes VARCHAR(2000), preliminary_taxon VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK (expected_count >= 0), CHECK ((latitude IS NULL AND longitude IS NULL) OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)))",
                "CREATE UNIQUE INDEX uq_event_field_number ON collection_event(field_number)",
                "CREATE TABLE event_collector(event_id BIGINT NOT NULL REFERENCES collection_event(id) ON DELETE CASCADE, person_id BIGINT NOT NULL REFERENCES person(id), ordinal INT NOT NULL, PRIMARY KEY(event_id, person_id), UNIQUE(event_id, ordinal))",
                "CREATE TABLE accession_number(number VARCHAR(100) PRIMARY KEY, numeric_part BIGINT, state VARCHAR(20) NOT NULL, reserved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, assigned_at TIMESTAMP, printed_at TIMESTAMP)",
                "CREATE TABLE specimen(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id BIGINT NOT NULL REFERENCES collection_event(id), accession_number VARCHAR(100) NOT NULL UNIQUE REFERENCES accession_number(number), taxon_group VARCHAR(100), preliminary_taxon VARCHAR(500), quantity INT NOT NULL DEFAULT 1, sex VARCHAR(100), life_stage VARCHAR(100), substrate VARCHAR(1000), comments VARCHAR(2000), report_intent VARCHAR(20) NOT NULL DEFAULT 'INCLUDE', archived BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK (quantity > 0))",
                "CREATE TABLE determination(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, specimen_id BIGINT NOT NULL REFERENCES specimen(id) ON DELETE CASCADE, taxon_name VARCHAR(500) NOT NULL, dyntaxa_id BIGINT, determiner_id BIGINT REFERENCES person(id), determination_year INT, kind VARCHAR(20) NOT NULL, uncertain BOOLEAN NOT NULL DEFAULT FALSE, notes VARCHAR(2000), is_current BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                "CREATE INDEX ix_determination_specimen ON determination(specimen_id, is_current)",
                "CREATE TABLE photo(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id BIGINT NOT NULL REFERENCES collection_event(id) ON DELETE CASCADE, file_name VARCHAR(255) NOT NULL, relative_path VARCHAR(1000) NOT NULL, sha256 VARCHAR(64), caption VARCHAR(1000), UNIQUE(relative_path))",
                "CREATE TABLE import_batch(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_file VARCHAR(1000) NOT NULL, source_sha256 VARCHAR(64), imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, added_count INT NOT NULL, skipped_count INT NOT NULL, failed_count INT NOT NULL)",
                "CREATE TABLE source_record(source_system VARCHAR(30) NOT NULL, source_id VARCHAR(255) NOT NULL, fingerprint VARCHAR(1000), event_id BIGINT REFERENCES collection_event(id), specimen_id BIGINT REFERENCES specimen(id), import_batch_id BIGINT REFERENCES import_batch(id), PRIMARY KEY(source_system, source_id))",
                "CREATE UNIQUE INDEX uq_source_fingerprint ON source_record(source_system, fingerprint)",
                "CREATE TABLE label_print(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label_type VARCHAR(30) NOT NULL, target_id BIGINT NOT NULL, copies INT NOT NULL, content_hash VARCHAR(64) NOT NULL, output_path VARCHAR(1000), printed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                "CREATE INDEX ix_label_target ON label_print(label_type, target_id, printed_at)",
                "CREATE TABLE report_export(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, output_path VARCHAR(1000) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, row_count INT NOT NULL)",
                "CREATE TABLE report_export_item(export_id BIGINT NOT NULL REFERENCES report_export(id) ON DELETE CASCADE, specimen_id BIGINT NOT NULL REFERENCES specimen(id), payload_hash VARCHAR(64) NOT NULL, PRIMARY KEY(export_id, specimen_id))",
                "CREATE TABLE report_confirmation(specimen_id BIGINT PRIMARY KEY REFERENCES specimen(id), payload_hash VARCHAR(64) NOT NULL, artportalen_id VARCHAR(255), confirmed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                "INSERT INTO collection_setting(setting_key, setting_value) VALUES ('owner.fullName','Nils Ericson'),('owner.shortName','N. Ericson'),('artportalen.privateCollection','Nils Ericson'),('accession.prefix','NE'),('accession.next','1'),('timezone','Europe/Stockholm')",
                "INSERT INTO person(full_name, short_name, artportalen_name) VALUES ('Nils Ericson','N. Ericson','Nils Ericson')",
                "INSERT INTO schema_version(version) VALUES (1)"
        };
        try (Statement s = c.createStatement()) {
            for (String sql : statements) s.execute(sql);
        }
    }

    /**
     * The local copy of the Dyntaxa checklist. One row per searchable string - a scientific name or a
     * vernacular one - carrying everything the suggestion list needs, because the table is rewritten
     * wholesale from a downloaded archive and never edited, so nothing can drift out of step.
     * search_name is the lowercased form the queries match on: H2 has no expression indexes, so the
     * normalised value has to be a stored column.
     */
    private static void createVersionTwo(Connection c) throws SQLException {
        String[] statements = {
                "CREATE TABLE taxon_name(search_name VARCHAR(300) NOT NULL, name VARCHAR(300) NOT NULL, authorship VARCHAR(200), dyntaxa_id BIGINT NOT NULL, kind VARCHAR(12) NOT NULL, accepted_id BIGINT, accepted_name VARCHAR(300), taxon_rank VARCHAR(40), taxonomic_status VARCHAR(40))",
                "CREATE INDEX ix_taxon_name_search ON taxon_name(search_name)",
                "INSERT INTO schema_version(version) VALUES (2)"
        };
        try (Statement s = c.createStatement()) {
            for (String sql : statements) s.execute(sql);
        }
    }

    @Override
    public synchronized void close() throws SQLException {
        closed = true;
        closeConnection();
    }

    private void closeConnection() throws SQLException {
        if (connection != null) {
            connection.close();
            connection = null;
        }
    }
}
